#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 26 22:13:25 2021

@author: richardhardy
"""
import json

data = {
    "Name": "Neil Armstrong",
    "Age": 82,
    "Hobbies": ["Aircraft design", "Fishing", "Astronaut"]
}
with open("neil.json", "w") as f:
    json.dump(data, f)
